HW1 answer
george007361/C-CPP_HW_ParkMailRu pull request #1
Opened 2021-10-14 20:37 UTC by george007361

Готово

2021-10-14 20:54 UTC, poofik33 requested changes
В репозитории сделанный вариант не сходится с тем, что и в README.
Уже слышал от студентов о такой проблеме, что вариант на сайте спустя время сменился, по какой-то причину

2021-10-14 20:54 UTC, poofik33 commented on computers.c
> +  List *list = (List *)malloc(sizeof(List));
Нет проверки на нулевой указатель

2021-10-14 20:54 UTC, poofik33 commented on computers.c
> +  Node *tmp = (Node *)malloc(sizeof(Node));
Нет проверки на нулевой указатель

2021-10-14 20:54 UTC, poofik33 commented on computers.h
> +#include <string.h>
Заголовки которые не нужны для объявления функций - в c файлы

2021-10-14 20:54 UTC, poofik33 commented on main.c
> +        if (!addComputer(computers)) printf("Error while adding car\n");
вывод ошибок можно вынести в stderr через fprintf

2021-10-14 20:54 UTC, poofik33 commented on main.c
> +  return 0;
reutrn EXIT_SUCCESS; <stdlib.h>

2021-10-14 20:54 UTC, poofik33 commented on menu.h
> +#define DEBUG_MENU 0
дефайны, кроме тех что определяют заголовчный файл - под инклюды

2021-10-14 21:04 UTC, poofik33 requested changes
Используется частично camelCase но в C snake_case

2021-10-14 21:04 UTC, poofik33 commented on computers.c
> +  return 1;
Все свои коды возврата из функций лучше обозначить через дефайны или enum

2021-10-14 21:04 UTC, poofik33 commented on computers.c
> +int delElem(PC *data, List *list, const int index) {
Я бы назвал это не delElem а pop - так как ты вытаскиваешь его из списка при этом сохраняешь значение

2021-10-14 21:04 UTC, poofik33 commented on computers.c
> +  List *list = (List *)malloc(sizeof(List));
Из-за того что нет проверки здесь, ее нет и в других местах, где сама функция вызывается

2021-10-14 21:04 UTC, poofik33 commented on computers.c
> +int delElem(PC *data, List *list, const int index) {
Увидел что есть уже Pop, а здесь вытаскивается элемент по индексу. Тогда лучше что то вроде get_and_remove

2021-10-23 12:21 UTC, leshiy1295 requested changes
честно говоря, так и не понял, что делает программа :(

2021-10-23 12:21 UTC, leshiy1295 commented on .travis.yml
> +
сейчас запускается две сборки - для ветки и PR - это лишняя работа

2021-10-23 12:21 UTC, leshiy1295 commented on .travis.yml
> +
последние сборки отменены => требование к прохождению CI не выполнено

2021-10-23 12:21 UTC, leshiy1295 commented on .travis.yml
> +      script: valgrind --tool=memcheck --leak-check=full ./main < ../in.txt
результат работы valgrind нужно проверять самостоятельно, т.к. он не падает при нахождении утечек (в отличие от санитайзеров)

2021-10-23 12:21 UTC, leshiy1295 commented on .travis.yml
> +
нет clang-tidy, clang-format, scan-build, fbinfer

2021-10-23 12:21 UTC, leshiy1295 commented on CMakeLists.txt
> +set(LIB_SOURCE_FILES computers.c)
если оформлять код как библиотеку, то стоит все файлы этой библиотеки вынести как минимум в отдельную директорию, и там расположить свой CMake

2021-10-23 12:21 UTC, leshiy1295 commented on CMakeLists.txt
> +add_subdirectory(./gtest)
лучше tests, gtest - это "утечка абстракции"...

2021-10-23 12:21 UTC, leshiy1295 commented on README.md
> +READY FOR WORK
зачем Вы нас дезинформируете? Если вариант поменялся, то нужно было хотя бы "своими словами" описать решённую задачу. Какой смысл в этой формулировке, если решалась другая задача?

2021-10-23 12:21 UTC, leshiy1295 commented on computers.c
> +  *list = (List *)malloc(sizeof(List));
list может быть NULL

2021-10-23 12:21 UTC, leshiy1295 commented on computers.c
> +
непонятно, что init_list делает в computers.c

2021-10-23 12:21 UTC, leshiy1295 commented on computers.c
> +  return 1;
0 и 1 - магические константы

2021-10-23 12:21 UTC, leshiy1295 commented on computers.c
> +  (*list)->head = (*list)->tail = NULL;
лучше избегать подобных конструкций

2021-10-23 12:21 UTC, leshiy1295 commented on computers.c
> +#endif  // DEBUG
?

2021-10-23 12:21 UTC, leshiy1295 commented on computers.c
> +int get_elem(Node **data, List *list, const int index) {
index можно было бы сделать size_t, тогда и проверка на входной контракт не требовалась бы. + const для копируемых значений обычно излишен и позволяет только гарантировать неизменность значения этого аргумента (копии исходного) внутри функции

2021-10-23 12:21 UTC, leshiy1295 commented on computers.c
> +  for (size_t i = 0; i < index; i++) {
я правильно понимаю, что size_t i сравнивается с int index?
я не верю, что не выдаётся никаких предупреждений от компилятора/анализаторов...

2021-10-23 12:21 UTC, leshiy1295 commented on computers.c
> +  *data = elem->val;
я не очень понимаю, зачем здесь снова дублируется логика работы со списком.
Стоило сделать отдельный слой со всеми операциями на списках. А на слое доменной логики уже передавать туда конкретные структуры, не заботясь о том, как эти списки работают

2021-10-23 12:21 UTC, leshiy1295 commented on computers.c
> +    get_and_remove(&tmp, (*list), 0);
сами сделали функцию, а используете её, как процедуру

2021-10-23 12:21 UTC, leshiy1295 commented on computers.c
> +      Node *data;
все переменные стоит явно инициализировать при определении

2021-10-23 12:21 UTC, leshiy1295 commented on computers.c
> +}
сейчас функция работает напрямую с stdout => нетестируема

2021-10-23 12:21 UTC, leshiy1295 commented on computers.c
> +    ;
функция print точно не должна ожидать ввода от пользователя

2021-10-23 12:21 UTC, leshiy1295 commented on computers.c
> +int add_computer(List *computers) {
функция добавления компьютера не должна ничего выводить или вводить

2021-10-23 12:21 UTC, leshiy1295 commented on computers.c
> +  scanf(SECURE_READ, &new_pc.name);
scanf - это функция

2021-10-23 12:21 UTC, leshiy1295 commented on computers.c
> +  scanf(SECURE_READ, &new_pc.name);
искусственно ограничивать максимальную длину строки нельзя - программа должна работать корректно с любым размером данных

2021-10-23 12:21 UTC, leshiy1295 commented on gtesting.cpp
> +  push_tail(list, tmp2);
использовать tmp1, tmp2... - плохо. Легко опечататься, смысл этих переменных не ясен + сейчас комментарий дублирует логику - можно было бы задать последовательность индексов массивом и в цикле по нему пройтись и всё добавить, разместив все эти tmp в отдельном массиве...

2021-10-23 12:21 UTC, leshiy1295 commented on gtesting.cpp
> +    switch (i / 3) {
тут точно /, а не %?

2021-10-23 12:21 UTC, leshiy1295 commented on gtesting.cpp
> +        EXPECT_TRUE(!strcmp(tmp->val.name, "fst"));
магические константы... Если это что-то, заданное в tmp1/2/3, то их и стоило тут использовать

2021-10-23 12:21 UTC, leshiy1295 commented on in.txt
> +1
тоже должно находиться в отдельной директории

2021-10-23 12:21 UTC, leshiy1295 commented on main.c
> +  Menu menu = init_menu(3, "ADD", "OUT", "EXIT");
а если бы было больше опций, пришлось бы изменить всю эту функцию?
стоило сделать массивом структур, в которых указывались бы название команды и указатель на функцию-обработчик

2021-10-23 12:21 UTC, leshiy1295 commented on menu.c
> +  free(menu->items);
ещё раз напоминаю про необходимость проверки входных аргументов

2021-11-07 19:37 UTC, closed without merging